Repository arc-pune/arc-front-end, pull requests merged in 2021-10, with the labels that each got.

#65 Delete dog.png
  src/components/Cards.js
  src/components/images/dog.png
  src/components/images/location.png
Labels: hacktoberfest-accepted

#74 #24: added mobile designs
  design/Mobile/About - mobile.png
  design/Mobile/Adopt - mobile.png
  design/Mobile/Home - mobile.png
  design/Mobile/Login - mobile.png
  design/Mobile/Pet Details - mobile.png
  design/Mobile/Signup - mobile.png
Labels: hacktoberfest-accepted

#75 Responsive
  src/pages/login.css
  src/pages/login.js
Labels: hacktoberfest, hacktoberfest2021

#92 login page needs a back button (#59):
  src/pages/login.css
  src/pages/login.js
Labels: hacktoberfest, hacktoberfest-accepted
